const setBtn = document.getElementById('set-btn')
const projectNameInput = document.getElementById('project-name')
const deadlineDateInput = document.getElementById('deadline-date')
const projectTitle = document.getElementById('project-title')
const daysEl = document.getElementById('days')
const hoursEl = document.getElementById('hours')
const minutesEl = document.getElementById('minutes')
const secondsEl = document.getElementById('seconds')
const messageEl = document.getElementById('message')

